### PR TITLE
Update version number for Skylab v8

### PR DESCRIPTION
**Pull request by svahl991**
## Description

Update version number in CMakeLists.txt

### CODE REVIEW

**Review by climbfuji — CHANGES_REQUESTED** [review]
@liujake You mentioned previously that we need to communicate version number updates for mpas-jedi and associated repos. The last tag was 3.0.0, if we follow semantic versioning rules we'd be making this 3.1.0 (and not 4.0.0). Any objections? Do we need to add labels such as `.jcsda` and `.mmm` to the version number, or prefixes?

**Comment by svahl991** [comment]
Yes I wasn't sure whether to go with v3.1 or v4.0. I just noticed that the last PR update was from 1.0 to 3.0, so I went with 4.0.

**Comment by liujake** [comment]
@svahl991 @climbfuji I'd prefer you tag your code/data release numbers with .jcsda or .skylab-v8. We may tag ours with .mmm.

**Comment by climbfuji** [comment]
Let's use 3.1.0.jcsda then - consistent with [1.2.0.jcsda](https://github.com/JCSDA/GFDL_atmos_cubed_sphere/releases/tag/1.2.0.jcsda)

**Comment by liujake** [comment]
fine with me.

**Review by shlyaeva — APPROVED** [review]
Agree to version 3.1.0 and tag 3.1.0.jcsda. Thank you for weighing in @climbfuji and @liujake !

**Review by climbfuji — APPROVED** [review]

**Review by ncrossette — APPROVED** [review]

**Review by liujake — APPROVED** [review]

**Pull request merged**
